גודל_במטר:
  מינימום: 96
  מקסימום: 150
חדרים:
  מינימום: 4.0
  מקסימום: 5.0
חיפוש:
  madlan_url: https://www.madlan.co.il/for-sale/%D7%92%D7%91%D7%A2%D7%AA%D7%99%D7%99%D7%9D-%D7%99%D7%A9%D7%A8%D7%90%D7%9C?bbox=34.78877%2C32.05844%2C34.82968%2C32.08181&filters=_0-4000000_4-5____parking%2Celevator%2CsecureRoom___90-__0-100000_______search-filter-top-bar&tracking_search_source=map&marketplace=residential
  מילות_חיפוש_קבוצות:
  - דירות למכירה
  - נדלן
  מיקום: גבעתיים
מחיר:
  מינימום: 3000000
  מקסימום: 4000000
  רק_פוסטים_עם_מחיר: true
מילות_חסימה:
- שותפים
- שותף
- דרושים
- מבוקש
מילות_מפתח_חובה: []
מילות_מפתח_רצויות:
- ממ"ד
- מרחב מוגן
- חניה
- מרפסת
- מעלית
- שמש
- מחסן
סריקה:
  כל_כמה_שעות: 2
  מקסימום_פוסטים_לקבוצה: 50
